CREATE TABLE tb_bill (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(50) NOT NULL,
	bar_code varchar(200) not null,
    value numeric(10,2) default(0.0) not null,
	payment_day date,
	payment_limit date not null
);
ALTER TABLE tb_bill ADD CONSTRAINT uk_bill_bar_code UNIQUE (bar_code);


-- insert into tb_bill(name, bar_code, value, payment_limit) values ('carlos', 'codigo de barra', 205.00, '2023-09-09');


-- select * from tb_bill
-- drop table tb_bill